<?php

namespace EDUBundle\Repository;

/**
 * ClassSubjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClassSubjectRepository extends \Doctrine\ORM\EntityRepository
{
}
