<?php

namespace EDUBundle\Repository;

/**
 * TeacherSubjectsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeacherSubjectsRepository extends \Doctrine\ORM\EntityRepository
{
}
