<?php

namespace EDUBundle\Repository;

/**
 * UsersTokensRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersTokensRepository extends \Doctrine\ORM\EntityRepository
{
}
